
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/kustomize kustomize

function gam() { "/Users/frode/bin/gam/gam" "$@" ; }
