command_timeout = 1000

[kubernetes]
symbol = "☸︎ "
style = "#326CE5"
disabled = false

[aws]
style = "#ff9900"
[aws.region_aliases]
ap-southeast-2 = "apse2"

[time]
disabled = false

[status]
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[python]
disabled = true

[gcloud]
symbol = "️🅶 "
format = 'on [$symbol$project]($style) '

[java]
disabled = true

