[font]
size = 18
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

#[general]
#import = ["/nix/store/jyngs0f87010wxkqskm0xc74z0i0npyz-source/themes/catppuccin_frappe.toml"]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
option_as_alt = "OnlyLeft"

#[[keyboard.bindings]]
#key = "Return"
#mods = "Shift"
#chars = "\x1b\r"
[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "PageUp"
mods = "Alt|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Alt|Shift"
action = "ScrollLineDown"
